apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-servicer-service-account

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dply-svc-roles
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dply-svc-roles
subjects:
- kind: ServiceAccount
  name: deployment-servicer-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: dply-svc-roles
  apiGroup: rbac.authorization.k8s.io

